#!/usr/bin/env bash

# Shortcuts

alias tmux='tmux -2'
alias tm='tmux -2'
alias r=ranger
alias h=htop
alias v=nvim
alias n=nvim
alias t=tig
alias less="less -R"
alias ccat='pygmentize -g'
alias pcat='pygmentize -g'
# alias git=gitsafe
# alias g=gitsafe
alias pg="ping 8.8.8.8"
alias hist=history

# Interactive modes
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# fasd
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection
alias j=z
alias jj=zz

# Search
alias agl='ag --pager="less -R"'  # Adds a pager to prevent flooding the terminal

# Copy/Paste
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# Trim new lines and copy to clipboard
alias c="tr -d '\n' | pbcopy"
alias -g C="| c"

# Command line head / tail shortcuts
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less -R"
alias -g M="| most"
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"
alias -g P="2>&1| pygmentize -l pytb"

alias dud='du -d 1 -h'
alias duf='du -sh *'
# alias fd='find . -type d -name'
alias ff='find . -type f -name'

# Static Webserver
alias pyserve='python -m SimpleHTTPServer 8080'

alias lock='gnome-screensaver-command -l'

# IP addresses
alias ip-public="dig +short myip.opendns.com opendns.com"
alias ip-local="ip addr show wlp2s0"
alias ip-list="ip addr show | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# Job related alisases
alias vsh='ssh devbox'
alias ash='airlab ssh'
alias vu='cd ~/airlab && vagrant up'
alias vp='cd ~/airlab && vagrant provision'
alias gk='goldkey'

# Haskell
alias ghc='stack exec -- ghc'
alias ghci='stack exec -- ghci'
# alias ghc-mod='stack exec -- ghc-mod'

# NVM
# alias loadnvm=\."$NVM_DIR/nvm.sh" && \. "$NVM_DIR/bash_completion"

alias glances='docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it docker.io/nicolargo/glances'

# Dev pitch
# alias awss='aws-vault --backend=pass exec -m `ykman oath code --single AWS_test` --no-session pitch_admin -- aws'
