#!/usr/bin/env bash

# Shortcuts

alias tmux='tmux -2'
alias tm='tmux -2'
alias r=ranger
alias h=htop
alias v=nvim
alias n=nvim
alias t=tig
alias less="less -R"
# alias git=gitsafe
# alias g=gitsafe
alias pg="ping 8.8.8.8"
alias hist=history

# Interactive modes
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# fasd
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection
alias j=z
alias jj=zz

# Trim new lines and copy to clipboard
alias c="tr -d '\n' | pbcopy"
alias -g C="| c"

# Command line head / tail shortcuts
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less -R"
alias -g M="| most"
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"
alias -g P="2>&1| pygmentize -l pytb"

alias dud='du -d 1 -h'
alias duf='du -sh *'
alias fd='find . -type d -name'
alias ff='find . -type f -name'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# Job related alisases
alias vsh='ssh devbox'
alias vu='cd ~/airlab && vagrant up'
alias vp='cd ~/airlab && vagrant provision'
alias gk='goldkey'

# Passwords
alias k='kp -d ~/passwords/db.kdb'
